# Generated by Django 5.0.4 on 2024-06-08 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blog_description_alter_blog_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="slug",
        ),
    ]
