# Generated by Django 5.0.4 on 2024-06-08 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_product_photo_alter_product_purchase_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="slug",
        ),
    ]
