# Generated by Django 5.0.4 on 2024-06-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_remove_product_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Введите название категории",
                max_length=100,
                null=True,
                verbose_name="Имя категории",
            ),
        ),
    ]
