# Generated by Django 5.0.4 on 2024-06-08 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_alter_category_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Version",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                (
                    "version_name",
                    models.CharField(
                        help_text="Введите Название версии",
                        max_length=100,
                        verbose_name="Название версии",
                    ),
                ),
                ("current_version", models.BooleanField(default=False)),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Выберите продукт",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="catalog.product",
                        verbose_name="Продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Версия",
                "verbose_name_plural": "Версии",
                "ordering": ["version_number"],
            },
        ),
    ]
