# Generated by Django 5.0.4 on 2024-06-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="version",
            name="current_version",
            field=models.BooleanField(default=False, verbose_name="Текущая версия"),
        ),
    ]
