# Generated by Django 5.0.4 on 2024-06-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0011_alter_version_version_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="version",
            name="version_number",
            field=models.PositiveIntegerField(
                help_text="Введите Номер версии",
                unique=True,
                verbose_name="Номер версии",
            ),
        ),
    ]
